apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  name: test-default-location-recurring-backup
spec:
  resourceSetName: rancher-resource-set-basic
  schedule: "@every 2m"
  retentionCount: 3