{{ if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") .Values.monitoring.alerts.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "backupRestore.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  groups:
    - name: backup-restore
    {{- with .Values.monitoring.alerts.alertingRules }}
      rules:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
